// src/lib/specialties.ts

import {
  Stethoscope, Baby, Brain, Bone, Heart, Smile, Bot, Droplets, Activity, Wind, Microscope, Shield, User,
  Users, Eye, Scissors, HeartCrack, Syringe, Dna, Utensils, Waves, PersonStanding, GitBranch,
  FlaskConical, Radiation, ShieldCheck, Footprints, Cloudy, Anchor, MessageSquare, TestTube,
  GitMerge, Atom, Zap, HelpingHand, VenetianMask, Leaf, HeartHandshake, Skull, Puzzle,
  Tractor, Weight
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Specialty {
  name: string;
  icon: LucideIcon;
  keywords: string[];
}

export const clinicalSpecialties: Specialty[] = [
  { name: 'Adult Bone Marrow Transplantation', icon: GitMerge, keywords: ['bone marrow', 'transplant', 'adult', 'hematology', 'oncology'] },
  { name: 'Adult Intensive Care Unit', icon: User, keywords: ['icu', 'critical care', 'adult', 'intensive care'] },
  { name: 'Anesthesiology', icon: Zap, keywords: ['anesthesia', 'pain management', 'surgery'] },
  { name: 'Bariatric and Metabolic Surgery', icon: Weight, keywords: ['bariatric', 'weight loss', 'metabolic surgery', 'obesity'] },
  { name: 'Breast', icon: User, keywords: ['breast', 'mammography', 'breast cancer', 'oncology'] },
  { name: 'Kidney Transplant', icon: GitBranch, keywords: ['kidney', 'transplant', 'nephrology', 'renal'] },
  { name: 'Cardiac Sciences', icon: Heart, keywords: ['cardiac', 'heart', 'cardiology'] },
  { name: 'Genetics', icon: Dna, keywords: ['genetics', 'dna', 'hereditary', 'genome'] },
  { name: 'Nutrition and Dietetics', icon: Utensils, keywords: ['nutrition', 'diet', 'dietitian', 'food'] },
  { name: 'Co-Lab', icon: FlaskConical, keywords: ['lab', 'laboratory', 'testing', 'diagnosis'] },
  { name: 'Dentistry', icon: Smile, keywords: ['dental', 'tooth', 'teeth', 'gums', 'dentist'] },
  { name: 'Dermatology and Cosmetology', icon: VenetianMask, keywords: ['dermatology', 'skin', 'cosmetic', 'acne', 'rash'] },
  { name: 'Emergency Medicine', icon: HelpingHand, keywords: ['emergency', 'er', 'trauma', 'urgent care'] },
  { name: 'Endocrinology', icon: Activity, keywords: ['endocrinology', 'hormones', 'diabetes', 'thyroid'] },
  { name: 'ENT Head & Neck Institute', icon: User, keywords: ['ent', 'ear', 'nose', 'throat', 'head', 'neck'] },
  { name: 'Family Medicine', icon: Users, keywords: ['family medicine', 'general practice', 'gp'] },
  { name: 'Gastroenterology', icon: Cloudy, keywords: ['gastroenterology', 'stomach', 'gut', 'digestion'] },
  { name: 'Gastrointestinal Surgery', icon: Scissors, keywords: ['gi surgery', 'gastrointestinal', 'stomach surgery'] },
  { name: 'General and Laparoscopic Surgery', icon: Scissors, keywords: ['general surgery', 'laparoscopic', 'minimally invasive'] },
  { name: 'General Medicine', icon: Stethoscope, keywords: ['general medicine', 'internal medicine', 'primary care'] },
  { name: 'Genesis International Fetal Medicine', icon: Baby, keywords: ['fetal medicine', 'prenatal', 'genesis'] },
  { name: 'HBOT (Hyperbaric Oxygen Therapy)', icon: Waves, keywords: ['hbot', 'hyperbaric', 'oxygen therapy'] },
  { name: 'Hematology', icon: Droplets, keywords: ['hematology', 'blood', 'anemia', 'leukemia'] },
  { name: 'Hepatopancreatobiliary Surgery and Transplantation', icon: GitMerge, keywords: ['hpb', 'liver', 'pancreas', 'biliary', 'transplant'] },
  { name: 'Infectious Diseases', icon: Shield, keywords: ['infectious disease', 'virus', 'bacteria', 'infection'] },
  { name: 'Internal Medicine', icon: Stethoscope, keywords: ['internal medicine', 'general care', 'adult medicine'] },
  { name: 'Medical Oncology', icon: ShieldCheck, keywords: ['oncology', 'cancer', 'chemotherapy', 'medical oncology'] },
  { name: 'Naturopathy', icon: Leaf, keywords: ['naturopathy', 'natural medicine', 'holistic'] },
  { name: 'Neonatology', icon: Baby, keywords: ['neonatology', 'newborn', 'infant', 'nicu'] },
  { name: 'Nephrology', icon: GitBranch, keywords: ['nephrology', 'kidney', 'renal', 'dialysis'] },
  { name: 'Neurology', icon: Brain, keywords: ['neurology', 'brain', 'nerves', 'headache', 'stroke'] },
  { name: 'Neurosurgery', icon: Brain, keywords: ['neurosurgery', 'brain surgery', 'spine surgery'] },
  { name: 'Nuclear Medicine', icon: Atom, keywords: ['nuclear medicine', 'radiology', 'imaging'] },
  { name: 'Obstetrics and Gynecology', icon: User, keywords: ['obgyn', 'obstetrics', 'gynecology', 'pregnancy'] },
  { name: 'Ophthalmology', icon: Eye, keywords: ['ophthalmology', 'eye', 'vision', 'glaucoma'] },
  { name: 'Oral and Maxillofacial Surgery', icon: Skull, keywords: ['oral surgery', 'maxillofacial', 'jaw surgery'] },
  { name: 'Orthopedics and Sports Medicine', icon: Bone, keywords: ['orthopedics', 'sports medicine', 'bones', 'joints'] },
  { name: 'Palliative and Supportive Care', icon: HeartHandshake, keywords: ['palliative care', 'supportive care', 'hospice'] },
  { name: 'Pediatric Bone Marrow Transplantation', icon: GitMerge, keywords: ['pediatric', 'bone marrow', 'transplant', 'child'] },
  { name: 'Pediatric Cardiology', icon: Heart, keywords: ['pediatric cardiology', 'child heart', 'congenital heart disease'] },
  { name: 'Pediatric Endocrinology', icon: Activity, keywords: ['pediatric endocrinology', 'child hormones', 'growth disorders'] },
  { name: 'Pediatric Gastroenterology', icon: Cloudy, keywords: ['pediatric gastroenterology', 'child stomach', 'digestion issues'] },
  { name: 'Pediatric Hematology', icon: Droplets, keywords: ['pediatric hematology', 'child blood disorders', 'anemia'] },
  { name: 'Pediatric Intensive Care Unit', icon: Baby, keywords: ['picu', 'pediatric critical care', 'child intensive care'] },
  { name: 'Pediatric Neuroscience', icon: Brain, keywords: ['pediatric neuroscience', 'child brain', 'developmental neurology'] },
  { name: 'Pediatric Oncology', icon: ShieldCheck, keywords: ['pediatric oncology', 'child cancer', 'childhood cancer'] },
  { name: 'Pediatric Pulmonology', icon: Wind, keywords: ['pediatric pulmonology', 'child lungs', 'asthma'] },
  { name: 'Pediatric Surgery', icon: Scissors, keywords: ['pediatric surgery', 'child surgery'] },
  { name: 'Pediatrics', icon: Baby, keywords: ['pediatrics', 'child health', 'pediatrician'] },
  { name: 'Physical Medicine and Rehabilitation', icon: PersonStanding, keywords: ['pm&r', 'rehabilitation', 'physical therapy'] },
  { name: 'Physiotherapy, Pain Medicine & Advanced...', icon: Activity, keywords: ['physiotherapy', 'pain medicine', 'rehab'] },
  { name: 'Plastic, Reconstructive and Cosmetic Surgery', icon: VenetianMask, keywords: ['plastic surgery', 'reconstructive', 'cosmetic surgery'] },
  { name: 'Psychiatry', icon: MessageSquare, keywords: ['psychiatry', 'mental health', 'depression', 'anxiety'] },
  { name: 'Pulmonology', icon: Wind, keywords: ['pulmonology', 'lungs', 'breathing', 'copd'] },
  { name: 'Radiation Oncology', icon: Radiation, keywords: ['radiation oncology', 'cancer treatment', 'radiotherapy'] },
  { name: 'Radiology', icon: Microscope, keywords: ['radiology', 'x-ray', 'mri', 'imaging'] },
  { name: 'Rheumatology', icon: Bone, keywords: ['rheumatology', 'arthritis', 'autoimmune', 'joint pain'] },
  { name: 'Scoliosis Surgery at Paley Middle...', icon: Bone, keywords: ['scoliosis', 'spine surgery', 'paley'] },
  { name: 'Sports Injuries & Sports Medicine', icon: Footprints, keywords: ['sports injuries', 'sports medicine', 'athlete'] },
  { name: 'Surgical Oncology', icon: ShieldCheck, keywords: ['surgical oncology', 'cancer surgery'] },
  { name: 'Thalassemia & Sickle Cell Center', icon: HeartCrack, keywords: ['thalassemia', 'sickle cell', 'blood disorder'] },
  { name: 'Thoracic Surgery', icon: Wind, keywords: ['thoracic surgery', 'chest surgery', 'lung surgery'] },
  { name: 'Fertility', icon: Puzzle, keywords: ['fertility', 'ivf', 'reproduction'] },
  { name: 'Urology', icon: Anchor, keywords: ['urology', 'urinary', 'bladder', 'kidney'] },
  { name: 'Vascular Surgery', icon: Syringe, keywords: ['vascular surgery', 'veins', 'arteries', 'aneurysm'] },
  { name: 'Weight Management', icon: Tractor, keywords: ['weight management', 'obesity', 'diet'] },
];
