
// This file is generated by `next`.
// It contains types for all known `devDependencies` in `package.json`.
// See: https://nextjs.org/docs/pages/building-your-application/configuring/typescript#statically-typed-devdependencies
/// <reference types="@tailwindcss/typography" />
/// <reference types="@types/node" />
/// <reference types="@types/react" />
/// <reference types="@types/react-datepicker" />
/// <reference types="@types/react-dom" />
/// <reference types="@types/react-slick" />
/// <reference types="@types/uuid" />
/// <reference types="@types/ws" />
/// <reference types="genkit-cli" />
/// <reference types="postcss" />
/// <reference types="tailwindcss" />
/// <reference types="typescript" />
